blank_issues_enabled: true
contact_links:
  - name: evocas discussions
    url: https://github.com/evocas/community/discussions
    about: Provide feedback and suggestions, ask questions, and discuss with others
